# Generated by Django 4.1.4 on 2023-02-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_members_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'male'), ('Female', 'female')], max_length=100, null=True),
        ),
    ]
