# Generated by Django 4.1.4 on 2023-02-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_members_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='society',
            field=models.CharField(blank=True, choices=[('Non-Society', 'Non-Society'), ('Ibukun Olu/ Irepodun / Aanuoluwapo', 'Ibukun Olu/ Irepodun / Aanuoluwapo'), ('Victorious Disciples', 'Victorious Disciples'), ('New Generation In Christ', 'New Generation In Christ'), ('Hepzibah', 'Hepzibah'), ('Moboluwaduro', 'Moboluwaduro'), ('Amiable', 'Amiable'), ('Egbe Agba', 'Egbe Agba'), ('Oore-Ofe Itesiwaju', 'Oore-Ofe Itesiwaju'), ('Omo-Ogun Kristi Ifelodun', 'Omo-Ogun Kristi Ifelodun'), ('Victorious Disciples', 'Victorious Disciples'), ('Imole Ayo', 'Imole Ayo'), ('New Generation In Christ', 'New Generation In Christ')], max_length=100, null=True),
        ),
    ]
