# Generated by Django 4.1.4 on 2023-02-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_members_society'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Married', 'Married'), ('Single', 'Single'), ('Widowed', 'Widowed')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='members',
            name='residential_state',
            field=models.CharField(blank=True, choices=[('Abia State', 'Abia State'), ('Adamawa State', 'Adamawa State'), ('Akwa Ibom State', 'Akwa Ibom State'), ('Anambra State', 'Anambra State'), ('Bauchi State', 'Bauchi State'), ('Bayelsa State', 'Bayelsa State'), ('Benue State', 'Benue State'), ('Borno State', 'Borno State'), ('Cross River State', 'Cross River State'), ('Delta State', 'Delta State'), ('Ebonyi State', 'Ebonyi State'), ('Edo State', 'Edo State'), ('Ekiti State', 'Ekiti State'), ('Enugu State', 'Enugu State'), ('Gombe State', 'Gombe State'), ('Imo State', 'Imo State'), ('Jigawa State', 'Jigawa State'), ('Kaduna State', 'Kaduna State'), ('Kano State', 'Kano State'), ('Katsina State', 'Katsina State'), ('Kebbi State', 'Kebbi State'), ('Kogi State', 'Kogi State'), ('Kwara State', 'Kwara State'), ('Lagos State', 'Lagos State'), ('Nasarawa State', 'Nasarawa State'), ('Niger State', 'Niger State'), ('Ogun State', 'Ogun State'), ('Ondo State', 'Ondo State'), ('Osun State', 'Osun State'), ('Oyo State', 'Oyo State'), ('Plateau State', 'Plateau State'), ('Rivers State', 'Rivers State'), ('Sokoto State', 'Sokoto State'), ('Taraba State', 'Taraba State'), ('Yobe State', 'Yobe State'), ('Zamfara State', 'Zamfara State')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='society',
            field=models.CharField(blank=True, choices=[('Non-Society', 'Non-Society'), ('Ibukun Olu/ Irepodun / Aanuoluwapo', 'Ibukun Olu/ Irepodun / Aanuoluwapo'), ('Hepzibah', 'Hepzibah'), ('Victorious Disciples', 'Victorious Disciples'), ('Imole Ayo', 'Imole Ayo'), ('New Generation in Christ', 'New Generation in Christ'), ('Moboluwaduro', 'Moboluwaduro'), ('Amiable', 'Amiable'), ('Egbe Agba', 'Egbe Agba'), ('Oore-Ofe Itesiwaju', 'Oore-Ofe Itesiwaju'), ('Omo-Ogun Kristi Ifelodun', 'Omo-Ogun Kristi Ifelodun')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='positions',
            name='department',
            field=models.CharField(blank=True, choices=[('Not Applicable', 'Not Applicable'), ('Undefined', 'Undefined'), ('Media', 'Media'), ('Finance', 'Finance'), ('Security', 'Security'), ('Music', 'Music'), ('Ushering', 'Ushering'), ('DTM', 'DTM'), ('BSF', 'BSF'), ('Music', 'Music'), ('Transport', 'Transport'), ('Medical/Dispensary', 'Medical/Dispensary'), ('Building', 'Building'), ('membership', 'membership'), ('School management board', 'School management board'), ('Sunday School Department', 'Sunday School Department'), ('Social/ Entertainment', 'Social/ Entertainment'), ('welfare', 'welfare'), ('Social / Prison', 'Social / Prison'), ('Marriage', 'Marriage'), ('Secretariat', 'Secretariat'), ('Children', 'Children'), ('Teens', 'Teens'), ('Wmu', 'Wmu'), ('Mmu', 'Mmu'), ('Maintenance', 'Maintenance'), ('Evangelism', 'Evangelism'), ('Youths', 'Youths')], max_length=100, null=True),
        ),
    ]
