# Generated by Django 4.1.4 on 2023-02-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_members_marital_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abcfamilies',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='members',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='positions',
            name='department',
            field=models.CharField(blank=True, choices=[('Not Applicable', 'Not Applicable'), ('Undefined', 'Undefined'), ('Media', 'Media'), ('Finance', 'Finance'), ('Music', 'Music'), ('Ushering', 'Ushering'), ('DTM', 'DTM'), ('BSF', 'BSF'), ('Music', 'Music'), ('Transport', 'Transport'), ('Medical/Dispensary', 'Medical/Dispensary'), ('Building', 'Building'), ('membership', 'membership'), ('School management board', 'School management board'), ('Sunday School Department', 'Sunday School Department'), ('Social/ Entertainment', 'Social/ Entertainment'), ('welfare', 'welfare'), ('Social / Prison', 'Social / Prison'), ('Marriage', 'Marriage'), ('Secretariat', 'Secretariat'), ('Children', 'Children'), ('Teens', 'Teens'), ('Wmu', 'Wmu'), ('Mmu', 'Mmu'), ('Maintenance', 'Maintenance'), ('Evangelism', 'Evangelism'), ('Youths', 'Youths'), ('Lights and Sounds', 'Lights and Sounds')], max_length=100, null=True),
        ),
    ]
