
states = ['Abia State', 'Adamawa State', 'Akwa Ibom State', 'Anambra State', 'Bauchi State', 'Bayelsa State',
          'Benue State', 'Borno State', 'Cross River State', 'Delta State', 'Ebonyi State', 'Edo State',
          'Ekiti State', 'Enugu State', 'Gombe State', 'Imo State', 'Jigawa State', 'Kaduna State', 'Kano State',
          'Katsina State', 'Kebbi State', 'Kogi State', 'Kwara State', 'Lagos State', 'Nasarawa State', 'Niger State',
          'Ogun State', 'Ondo State', 'Osun State', 'Oyo State', 'Plateau State', 'Rivers State', 'Sokoto State',
          'Taraba State',
          'Yobe State', 'Zamfara State']

marital_status = ['Married', 'Single', 'Widowed']

society = ["Non-Society",
           "Ibukun Olu/ Irepodun / Aanuoluwapo",
           "Hepzibah",
           "Victorious Disciples",
           "Imole Ayo",
           "New Generation in Christ",
           "Moboluwaduro",
           "Amiable",
           "Egbe Agba",
           "Oore-Ofe Itesiwaju",
           "Omo-Ogun Kristi Ifelodun"]

departments = ["Not Applicable",
               "Undefined",
               "Media",
               "Finance",
               "Music",
               "Ushering", "DTM",
               "BSF", "Music", "Transport",
               'Medical/Dispensary',
               "Building",
               "membership",
               "School management board",
               "Sunday School Department",
               "Social/ Entertainment",
               "welfare",
               "Social / Prison",
               "Marriage",
               "Secretariat",
               "Children",
               "Teens", 'Wmu',
               'Mmu', "Maintenance",
               "Evangelism", "Youths",
               "Lights and Sounds"]
